### ISSUE TITLE
Crash on Start 0.5.3

### ISSUE THREAD

**Issue by DJDrWright** [MSandro/NeoForge-Foundry-StoneBlock-Edition#10]
Version 0.5.3, crash during load. Happened twice, uninstalled, reinstalled, happened on new install.

The game crashed while rendering overlay
Error: java.lang.IllegalArgumentException: No model for layer twilightforest:knightmetal_shield#main

Crash Log attached
[crash-2024-04-23_13.12.25-client.txt](https://github.com/MSandro/NeoForge-Foundry-StoneBlock-Edition/files/15081120/crash-2024-04-23_13.12.25-client.txt)

**Comment by MSandro** [comment]
I am really confused about this issue, could you please give us some system informations?
Launcher
OS
Allocated RAM
CPU
GPU

**Comment by SliverMessiah** [comment]
yeah im also having the same issue with the same crash log.

Launcher - CurseForge/Minecraft Launcher v.2.2214-1.9.2
OS - Win10
Allocated RAM - Xmx10000m
CPU - Intel I7-6700K
GPU - RTX 2070

It might have to do with that version of Twilight Forest.

**Comment by MSandro** [comment]
I can confirm the issue on Win11, we are developing the packs on Linux, it works well on OpenSuse and Debian and it should work on most other distributions.

 I know most players are using Windows, so i try to fix the issue asap.

**Comment by MSandro** [comment]
please remove the Mod ModernUI and let me know if it solves the Issue.

**Comment by MSandro** [comment]
Please let me know if 0.5.4 fixed the issue.
