### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by FILIPPETTO070707** [MSandro/NeoForge-Foundry-StoneBlock-Edition#12]
Hello i and my friend try to open the pack in the version 0.5.4 but crash instantly. Can you fix with the first release of the modpack. Thank you.

**Comment by MSandro** [comment]
A fix will be released tomorrow

**Comment by FILIPPETTO070707** [comment]
Thank you is working

**Comment by MSandro** [comment]
please try 0.5.6 and tell me if it works now.
