### ISSUE TITLE
PLS TELL ME HOW CAN I START A SERVER FOR ME AND MY FRIEND PLSSSSSSSS

### ISSUE THREAD

**Issue by PosaMan** [MSandro/NeoForge-Foundry-StoneBlock-Edition#13]
in the directory i saw 2 start files but i don't know what to do, I think that i need to find this file "forge 1.20.4 4-20.4.232.jar" BUT WHERE THE F''' IS RHIS FILE?? plz  https://maven.neoforged.net/releases/net/neoforged/neoforge/20.4.232/neoforge-20.4.232-installer.jar on this link i should be able to istall the file, but i don't know how to do that PLS HELP. Just tell me how and what i need to do in order to start a working for me and my friend.

**Comment by MSandro** [comment]
execute the start.sh (Linux) or start.ps1 (Windows) it will download all jar files and libs.
it will generate a run.sh (Linux) and run.bat (Windows) to start the server after the install process.

**Comment by PosaMan** [comment]
the problem is that that when i click run.but notting happens NOTTING :(

**Comment by 0gp** [comment]
Did you install the correct java version?
I know launching a minecraft server on Windows is a very stupid idea, but it works,  I was struggling a few minutes and now it works.

**Comment by PosaMan** [comment]
i will try thx

**Comment by PosaMan** [comment]
I will ask to my friend to try

**Comment by PosaMan** [comment]
wich java version is the correct one? thx for your time btw

**Comment by MSandro** [comment]
Java 17

**Comment by PosaMan** [comment]
ok thx now works fine
