### ISSUE TITLE
Crash pack after killing mobs

### ISSUE THREAD

**Issue by andry72** [MSandro/NeoForge-Foundry-StoneBlock-Edition#14]
Modpack crash after start killing some hostile mobs
Now the modpack if start after 11 second crash every time

[crash-2024-05-01_11.20.10-server.txt](https://github.com/MSandro/NeoForge-Foundry-StoneBlock-Edition/files/15175832/crash-2024-05-01_11.20.10-server.txt)

**Comment by andry72** [comment]
I've try to copy my world in my linux server and happend the same think

**Comment by MSandro** [comment]
please try v0.5.6, there are many mod updates and it should fix the issue.
