### ISSUE TITLE
Kambrik on a Forge Pack?

### ISSUE THREAD

**Issue by TheUntamed** [MSandro/NeoForge-Foundry-StoneBlock-Edition#15]
I have more of a question than an issue. (Sorry for posting here if it's the wrong place. Haven't seen a discussion section)
As far as I could take from the description, the mod Kambrik aims to simplify Fabric. But NeoForge Foundry: StoneFactory Edition is a Forge/NeoForge pack. Why is a Fabric related mod in this pack, what does it do?

**Comment by MSandro** [comment]
Kambrik is loading fine in NeoForge. I gues because a mod has it as requirement and Kambrik did a NeoForge port.
![image](https://github.com/MSandro/NeoForge-Foundry-StoneBlock-Edition/assets/10937159/7980976e-17a2-4ce2-9d74-cc1b79109776)
