### ISSUE TITLE
Neoforge triggering Bitdefender Antivirus?

### ISSUE THREAD

**Issue by rtr468** [MSandro/NeoForge-Foundry-StoneBlock-Edition#16]
Never had any issues with antivirus stopping my curseforge pack downloads, but every time I try do download any of the neoforge-foundry packs (base, skyblock, or stoneblock) my antivirus declares it has a trojan inside of it, and deletes all the files. Just curious if anyone else is getting this issue, and if theres anything I can do to help, say scan the whole file and figure out what exactly is infected. Thanks in advance!

**Comment by MSandro** [comment]
Thanks for reporting the issue. Some more details would be great.
It would be important to know if its caused by a specific mod or something else.

**Comment by MSandro** [comment]
closed because of no response
