### ISSUE TITLE
unable to complete bronze ingot bronze dust always smelts to mekanism ignots

### ISSUE THREAD

**Issue by 98kdodds** [MSandro/NeoForge-Foundry-StoneBlock-Edition#2]
enjoyable pack btw just a note 
bronze dust smelts to mekanism ignots no matter whether it is modern indust or mekanism dust
pack version 0.5.0

also tag errors on bronze cutting machine and lubricant tag and bronze  mixer reward tag all show up as purple backed question mark

**Comment by MSandro** [comment]
Fixed in 0.5.2
