### ISSUE TITLE
Dupping Copper Hammers - ModPack Version 0.5.0

### ISSUE THREAD

**Issue by SliverMessiah** [MSandro/NeoForge-Foundry-StoneBlock-Edition#3]
In the beginning of my play-through, i accidentally made 2 copper crack hammers. Ive been using them intensively to the point now that i wanted to combine them into one. i do get a new hammer but the old ones stay in the crafting table to infinity make new hammers.
![Copper Dupping](https://github.com/MSandro/NeoForge-Foundry-StoneBlock-Edition/assets/92107357/eb0dce67-e301-4413-ac27-be7d5322dbdf)

**Comment by MSandro** [comment]
Thanks for reporting this bug. I'm working on fixing it, but it's strange, I'm still not sure which mod is adding the repair-recipes.

**Comment by SliverMessiah** [comment]
Np. Btw do yall have a discord for this modpack or do you rather have all reports posted in the issues tab?

**Comment by MSandro** [comment]
The repairing recipes will be removed in v0.5.3
![image](https://github.com/MSandro/NeoForge-Foundry-StoneBlock-Edition/assets/10937159/5b7e3747-4a5a-4fe9-a59f-5d5debb54ea4)

Not at the moment, I plan to create a Discrod Server soon.
