### ISSUE TITLE
Loot Rewards Empty - ModPack Version 0.5.0

### ISSUE THREAD

**Issue by SliverMessiah** [MSandro/NeoForge-Foundry-StoneBlock-Edition#4]
Ive claimed 3 Loot rewards so far and they have been empty.
![Loot Rewards](https://github.com/MSandro/NeoForge-Foundry-StoneBlock-Edition/assets/92107357/d06be7d8-4cf2-4f40-aee9-4fec6d9767f0)

**Comment by MSandro** [comment]
Fixed in 0.5.2
It was wrong Reward Table ID.
