### ISSUE TITLE
Compressed sieve don't act like sieve

### ISSUE THREAD

**Issue by Thomas972** [MSandro/NeoForge-Foundry-StoneBlock-Edition#6]
Breaking a compressed sieve don't drop the mesh in it, but breaking a normal sieve drop it.
Right-click a normal sieve next to another with gravel fill the two sieves. Doing it with compressed sieves and compressed gravel only fill one sieve.

**Comment by MSandro** [comment]
I have reported it to ExDeorum

**Comment by MSandro** [comment]
In 0.5.3 the problem will be solved. But I will not enable simultaneous compressed sieve usage.
