### ISSUE TITLE
We can't buy cow spawn eggs in the marker

### ISSUE THREAD

**Issue by Thomas972** [MSandro/NeoForge-Foundry-StoneBlock-Edition#7]
JEI says that cow eggs costs 1 diamond in the market but the market don't show it.
![Capture d’écran du 2024-04-21 13-19-42](https://github.com/MSandro/NeoForge-Foundry-StoneBlock-Edition/assets/24301380/9536dda6-3583-40bb-b4cd-4a5fd37f63b6)
![Capture d’écran du 2024-04-21 13-20-37](https://github.com/MSandro/NeoForge-Foundry-StoneBlock-Edition/assets/24301380/e77738dc-f3c6-42c0-88df-3961f4014cbb)

**Comment by MSandro** [comment]
Getting spawn egs is disabled, not sure why it will be displayed in EMI.

I plan to make it easier to get Blessed earth in the next update. It is like cursed earth but it spawns animals.
https://www.curseforge.com/minecraft/mc-mods/cursed-earth-returns

**Comment by MSandro** [comment]
I am closing this because in 0.5.2 you can get Animals easy, and there is a new quests for getting Blessed Earth.
