### ISSUE TITLE
Wooden Shears Recipe - 0.5.1

### ISSUE THREAD

**Issue by SliverMessiah** [MSandro/NeoForge-Foundry-StoneBlock-Edition#8]
The wooden shears recipe is giving me Battered Sausage.
![Wooded Shears](https://github.com/MSandro/NeoForge-Foundry-StoneBlock-Edition/assets/92107357/83e18e69-db86-415e-99c8-ff7f236f8206)

(Edited)Actually almost every recipe is broken. Its either giving you Sawdust or Battered Sausage

**Comment by MSandro** [comment]
Duplicate of #1 
please re join your world.
