### ISSUE TITLE
Can't Launch Current Version - 0.5.2

### ISSUE THREAD

**Issue by SliverMessiah** [MSandro/NeoForge-Foundry-StoneBlock-Edition#9]
Getting crash error: 

> The game crashed whilst rendering overlay
> Error: java.lang.IllegalArgumentException: No model for layer twilightforest:knightmetal_shield#main

**Comment by MSandro** [comment]
interesting, which launcher are you using?

**Comment by MSandro** [comment]
I was able to reproduce the issue, launched 10 times and  it only happened once.
But I have a suspicion that a tweak from ModernFix could trigger this. I'll change this in 0.5.3 which should be released today.
